PMS_Application/PMS.WebApp/Areas/Callin/Pages/Group.cshtml.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PMS.Contract.Commons.UnitOfWorks;
using PMS.Contract.Signalr.Groups;
using PMS.Contract.Signalr.Messages;
using PMS.Contract.Systems.Users;
using PMS.Domain.Signalr;
using PMS.Domain.Systems;
using PMS.Infrastructure.EnityFrameworkCore;

namespace PMS.WebApp.Areas.Callin.Pages
{
    public class GroupModel : PageModel
    {
        private readonly PMSDbContext _context;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IUserService _userService;
        private readonly IGroupService _groupService;
		private readonly IHttpContextAccessor _httpContextAccessor;

		public GroupModel(PMSDbContext context,
           IMapper mapper,
           IUnitOfWork unitOfWork,
           IUserService userService,
           IGroupService groupService,
           IMessageService messageService
           )
        {
            _context = context;
            _mapper = mapper;
            _unitOfWork = unitOfWork;
            _userService = userService;
            _groupService = groupService;
        }
        [BindProperty(SupportsGet = true)]
        public List<GroupDto> GroupDtos { get; set; }
        [BindProperty(SupportsGet = true)]
        public UserDto CurrentUser { get; set; }  //User hiện tại
		[BindProperty(SupportsGet = true)]
		public CreateUpdateGroupDto CreateUpdateGroup { get; set; }

        [BindProperty]
        public int GroupId { get; set; }

        public async Task<IActionResult> OnGet()
        {

            var user = _context.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
            CurrentUser = _mapper.Map<AppUser, UserDto>(user);

			//var groups = _context.Groups.Include(x => x.Messages).Include(x => x.GroupUsers).ToList();

			var groups = _context.Groups.Where(g => g.GroupUsers.Any(gu => gu.UserId == user.Id)).Include(x => x.Messages).Include(x => x.GroupUsers).ToList();

			GroupDtos = _mapper.Map<List<GroupDto>>(groups);
			return Page();
        }

        public async Task<IActionResult> OnPostCreateGroup()
        {
            var createGroup = _mapper.Map<Group>(CreateUpdateGroup);
            await _groupService.InsertAsync(createGroup);
            await _unitOfWork.SaveChangesAsync();

            var userCreated = _context.Users.Where(x => x.UserName == createGroup.CreatedBy).FirstOrDefault();
            _context.GroupUsers.Add(new GroupUser
            {   
                UserId = userCreated.Id,
                GroupId = createGroup.Id,
                IsKey = true,
            });
			await _unitOfWork.SaveChangesAsync();

			return RedirectToPage();
        }

		public async Task<IActionResult> OnPostDeleteGroup()
		{
            var group = await _groupService.GetByIdAsync(GroupId);
			await _groupService.DeleteAsync(group);
			await _unitOfWork.SaveChangesAsync();


			return RedirectToPage();
		}

       
	}
}

PMS_Application/PMS.WebApp/Areas/Callin/Pages/Index.cshtml.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PMS.Contract.Commons.UnitOfWorks;
using PMS.Contract.Signalr.Groups;
using PMS.Contract.Signalr.Messages;
using PMS.Contract.Systems.Users;
using PMS.Domain.Signalr;
using PMS.Domain.Systems;
using PMS.Infrastructure.EnityFrameworkCore;
using System.Text.RegularExpressions;


namespace PMS.WebApp.Areas.Callin.Pages
{
    public class IndexModel : PageModel
    {
        private readonly PMSDbContext _context;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IUserService _userService;
        private readonly IGroupService _groupService;
        private readonly IMessageService _messageService;

        public IndexModel(PMSDbContext context,
            IMapper mapper,
            IUnitOfWork unitOfWork,
            IUserService userService,
            IGroupService groupService,
            IMessageService messageService)
        {
            _context = context;
            _mapper = mapper;
            _unitOfWork = unitOfWork;
            _userService = userService;
            _groupService = groupService;
            _messageService = messageService;
        }

		[BindProperty]
		public List<UserDto> Others { get; set; }

        [BindProperty]
        public UserDto CurrentUser { get; set; }  //User hiện tại

        [BindProperty(SupportsGet = true)]
        public List<UserDto> UserDtos { get; set; }  //List user cuar group hiện tại


        [BindProperty(SupportsGet = true)]
        public List<MessageDto> MessageDtos { get; set; }  // List message of Current group

		[BindProperty(SupportsGet = true)]
		public int CurrentGroupId { get; set; }  //Current groupId

        [BindProperty(SupportsGet = true)]
        public GroupDto CurrentGroup { get; set; }
        [BindProperty]
        public string AddOtherId { get; set; }

        public async Task<IActionResult> OnGet(int groupId)
        {
            CurrentGroupId = groupId;
            var group = _context.Groups.Where(x => x.Id == groupId).Include(x => x.Messages).Include(x => x.GroupUsers).FirstOrDefault();
            CurrentGroup = _mapper.Map<GroupDto>(group);


			var messages = _context.Messages.Include(m => m.Sender).Where(m => m.GroupId == CurrentGroupId).OrderBy(m => m.CreationTime).ToList();
			MessageDtos = _mapper.Map<List<Message>, List<MessageDto>>(messages);

			var users = _context.Users.Where(u => u.GroupUsers.Any(gu => gu.GroupId == groupId))
                                .Include(x => x.GroupUsers)
                                .ThenInclude(x => x.Group)
                                .ToList();
            UserDtos = _mapper.Map<List<UserDto>>(users);

            var user = _context.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
            CurrentUser = _mapper.Map<AppUser, UserDto>(user);

			// Lấy danh sách tất cả người dùng
			var allUsers = _context.Users.ToList();

			var usersInGroup = users.Select(m => m.Id).ToList();

			// Lấy danh sách các người dùng không thuộc vào group hiện tại
			Others = _mapper.Map<List<UserDto>>(allUsers.Where(u => !usersInGroup.Contains(u.Id)).ToList());


			return Page();
           
        }

        public async  Task<IActionResult> OnPost()
        {
			var messages = _context.Messages.Include(m => m.Sender).Where(m => m.GroupId == CurrentGroupId).OrderBy(m => m.CreationTime).ToList();
			MessageDtos = _mapper.Map<List<Message>, List<MessageDto>>(messages);
			return RedirectToPage();
		}

		public async Task<IActionResult> OnPostAddOther()
		{
            _context.GroupUsers.Add(new GroupUser
            {
                GroupId = CurrentGroupId,
                UserId = AddOtherId,
                IsKey = false,
            });
            await _unitOfWork.SaveChangesAsync();

			return RedirectToPage(new { groupId = CurrentGroupId });
		}
	}
}

PMS_Application/PMS.WebApp/Areas/Callin/Pages/Group.cshtml
@page
@model PMS.WebApp.Areas.Callin.Pages.GroupModel
@{
}




<link href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
<!--Group-->
<div class="main-wrapper">
	<div class="container">
		<div class="page-content">
			<div class="container mt-5">
				<div class="row">
					<div class="col-md-4 col-12 card-stacked">
						<div class="card shadow-line mb-3 chat">
							<div class="chat-user-detail">
								<div class="p-3 chat-header">
								</div>
							</div>
							<div class="p-3 chat-header">
								<div class="d-flex">
									<div class="w-100 d-flex pl-0">
										<!--Avatar-->
										<img class="user-detail-trigger rounded-circle shadow avatar-sm mr-3 chat-profile-picture" src="~/images/@Model.CurrentUser.Avatar" />
										<p>@Model.CurrentUser.FullName</p>
									</div>
									<div class="flex-shrink-0 margin-auto">
										<a role="button" id="create-room" data-bs-toggle="modal" data-bs-target="#create-room-modal" class="btn btn-sm btn-icon btn-light active text-dark ml-2">
											<!--Add group-->
											<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg>
										</a>
										<a asp-area="Identity" asp-page="/Account/Manage/Index" class="btn btn-sm btn-icon btn-light active text-dark ml-2">
											<!--Edit group-->
											<svg viewBox="0 0 24 24" width="15" height="15" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="feather">
												<path d="M12 20h9"></path>
												<path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"></path>
											</svg>
										</a>
									</div>
								</div>
							</div>
							<div class="chat-search pl-3 pr-3">
								<div class="input-group">
									<input type="text" class="form-control" placeholder="Search a conversation">
									<div class="input-group-append prepend-white">
										<span class="input-group-text pl-2 pr-2">
											<i class="fs-17 las la-search drop-shadow"></i>
										</span>
									</div>
								</div>
							</div>

							<div class="chat-user-panel">
								<div class="pb-3 d-flex flex-column navigation-mobile pagination-scrool chat-user-scroll">
									@foreach (var groupDto in Model.GroupDtos)
									{
										<div class="chat-item active d-flex pl-3 pr-0 pt-3 pb-3">
											<div class="w-100">
												<div class="d-flex pl-0">
													<img class="rounded-circle shadow avatar-sm mr-3" src="~/assets/img/theme/tim.png">
													<div>
														<p class="margin-auto fw-400 text-dark-75">@groupDto.Name</p>
														<div class="d-flex flex-row mt-1">
															<span>
																<div class="svg15 double-check"></div>
															</span>
															<span class="message-shortcut margin-auto text-muted fs-13 ml-1 mr-4">@groupDto.LastMassage</span>
														</div>
													</div>
												</div>
											</div>
											<div class="flex-shrink-0 margin-auto pl-2 pr-3">
												<div class="d-flex flex-column">
													@* <p class="text-muted text-right fs-13 mb-2">@groupDto.LastMassage</p> *@
													<div class="text-right d-flex flex-row">
														<a role="button" class="btn btn-close remove-group" data-groupid="@groupDto.Id" id="remove-room" data-bs-toggle="modal" data-bs-target="#remove-room-modal"></a>
														<i class="text-muted la la-angle-down ml-1 fs-15"></i>
													</div>
												</div>
											</div>
										</div>
										<a class="btn btn-success btn-sm" asp-page="./Index" asp-route-groupId="@groupDto.Id">Join Group</a>
									}

								</div>
							</div>
						</div>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>

<form method="post" asp-page-handler="createGroup">
	<div class="modal fade" id="create-room-modal" tabindex="-1" aria-labelledby="createRoomModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="createRoomModalLabel">Create Group</h5>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="modal-body">
					<input type="text" asp-for="CreateUpdateGroup.Name" class="form-control" id="roomName" maxlength="100" placeholder="Enter group name..." />
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-sm btn-secondary" data-bs-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-sm btn-primary" data-bs-dismiss="modal">Create</button>
				</div>
			</div>
		</div>
	</div>
</form>

<form method="post" asp-page-handler="deleteGroup">
	<input type="hidden" asp-for="GroupId" id="groupIdInput" value="GroupId">
	<div class="modal fade" id="remove-room-modal" tabindex="-1" aria-labelledby="removeRoomModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="removeRoomModalLabel">Delete Group</h5>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="modal-body">
					<p class="mb-0">Are you sure you want to delete this chat group?</p>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-sm btn-secondary" data-bs-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-sm btn-danger" data-bs-dismiss="modal">Delete</button>
				</div>
			</div>
		</div>
	</div>

</form>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.perfect-scrollbar/0.6.7/js/min/perfect-scrollbar.jquery.min.js"></script>

<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.bundle.min.js"></script>
<script>
	(function ($) {
		"use strict";
		$('.scrollable-chat-panel').perfectScrollbar();
		var position = $(".chat-search").last().position().top;
		$('.scrollable-chat-panel').scrollTop(position);
		$('.scrollable-chat-panel').perfectScrollbar('update');
		$('.pagination-scrool').perfectScrollbar();

		$('.chat-upload-trigger').on('click', function (e) {
			$(this).parent().find('.chat-upload').toggleClass("active");
		});
		$('.user-detail-trigger').on('click', function (e) {
			$(this).closest('.chat').find('.chat-user-detail').toggleClass("active");
		});
		$('.user-undetail-trigger').on('click', function (e) {
			$(this).closest('.chat').find('.chat-user-detail').toggleClass("active");
		});
	})(jQuery);
</script>

<script>
	$(document).ready(function () {
		$(".remove-group").click(function () {
			var groupId = $(this).data("groupid");
			$("#groupIdInput").val(groupId); // Set the groupId in the hidden input field
		});
	});
</script>





<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script src="~/js/chat.js"></script>

PMS_Application/PMS.WebApp/Areas/Callin/Pages/Index.cshtml
@page
@using Humanizer;
@using Microsoft.EntityFrameworkCore;
@model PMS.WebApp.Areas.Callin.Pages.IndexModel
@{
}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" rel="stylesheet">

<!--Group-->
<div class="main-wrapper">
	<div class="container">
		<div class="page-content">
			<div class="container mt-5">
				<div class="row">
					<div class="col-md-4 col-12 card-stacked">
						<div class="card shadow-line mb-3 chat">
							<div class="p-3 chat-header">
								<div class="d-flex">
									<div class="w-100 d-flex pl-0">
										<!--Avatar current user-->
										<img class="user-detail-trigger rounded-circle shadow avatar-sm mr-3 chat-profile-picture" src="~/images/@Model.CurrentUser.Avatar" />
										<p class="margin-auto fw-400 text-dark-75">@Model.CurrentUser.FullName</p>
									</div>

									<div class="flex-shrink-0 margin-auto">
										<a href="#" class="btn btn-sm btn-icon btn-light active text-dark ml-2">
											<svg viewBox="0 0 24 24" width="15" height="15" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="feather">
												<rect x="2" y="7" width="20" height="15" rx="2" ry="2"></rect>
												<polyline points="17 2 12 7 7 2"></polyline>
											</svg>
										</a>
										<a href="#" class="btn btn-sm btn-icon btn-light active text-dark ml-2">
											<svg viewBox="0 0 24 24" width="15" height="15" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="feather">
												<path d="M12 20h9"></path>
												<path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"></path>
											</svg>
										</a>
										<a href="#" class="btn btn-sm btn-icon btn-light active text-dark ml-2">
											<svg viewBox="0 0 24 24" width="15" height="15" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="feather">
												<circle cx="12" cy="12" r="1"></circle>
												<circle cx="12" cy="5" r="1"></circle>
												<circle cx="12" cy="19" r="1"></circle>
											</svg>
										</a>
									</div>
								</div>
							</div>
							<div class="chat-search pl-3 pr-3">
								<div class="input-group">
									<input type="text" class="form-control" placeholder="Search a conversation">
									<div class="input-group-append prepend-white">
										<span class="input-group-text pl-2 pr-2">
											<i class="fs-17 las la-search drop-shadow"></i>
										</span>
									</div>
								</div>
							</div>
							<div class="archived-messages d-flex p-3">
								<div class="w-100">
									<div class="d-flex pl-0">
										<div class="d-flex flex-row mt-1 mr-5">
											<span class="margin-auto mr-2">
												<div class="svg15 archived members-icon"></div>
											</span>
											<a id="members-button" role="button" class="margin-auto fw-500 text-dark-75 active">Members</a> <span style="width:70px"></p>
										</div>
										<div class="d-flex flex-row mt-1 ml-5">
											<span class="margin-auto mr-2">
												<div class="svg15 others-icon"></div>
											</span>
											<a id="others-button" role="button" class="margin-auto fw-400 text-dark-75">Others</a>
										</div>
										<div>
										</div>
									</div>
								</div>
							</div>
							<div class="chat-user-panel">
								<div class="pb-3 d-flex flex-column navigation-mobile pagination-scrool chat-user-scroll">
									<div class="members-list">
										@foreach (var userDto in Model.UserDtos)
										{
											<div class="chat-item active d-flex pl-3 pr-0 pt-3 pb-3">
												<div class="w-100">
													<div class="d-flex pl-0">
														<img class="rounded-circle shadow avatar-sm mr-3" src="~/images/@userDto.Avatar">
														<div>
															<p class="margin-auto fw-400 text-dark-75">@userDto.UserName</p>
															<div class="d-flex flex-row mt-1">
																<span>
																	<div class="svg15 double-check"></div>
																</span>
																<!--Last messsage-->
																<span class="message-shortcut margin-auto text-muted fs-13 ml-1 mr-4">@userDto.FullName</span>
															</div>
														</div>
													</div>
												</div>
												<div class="flex-shrink-0 margin-auto pl-2 pr-3">
													<div class="d-flex flex-column">
														<p class="text-muted text-right fs-13 mb-2">@userDto.CreationTime.Value.ToShortDateString()</p>
														<div class="text-right d-flex flex-row">
															<span>
																<i class="fa-regular fa-comment fa-bounce" style="color: #215bc0;"></i>
															</span>
															<i class="text-muted la la-angle-down ml-1 fs-15"></i>
														</div>
													</div>
												</div>
											</div>

										}
									</div>
									<div class="others-list" style="display: none;">
										@foreach (var userDto in Model.Others)
										{
											<div class="chat-item active d-flex pl-3 pr-0 pt-3 pb-3">
												<div class="w-100">
													<div class="d-flex pl-0">
														<img class="rounded-circle shadow avatar-sm mr-3" src="~/images/@userDto.Avatar">
														<div>
															<p class="margin-auto fw-400 text-dark-75">@userDto.UserName</p>
															<div class="d-flex flex-row mt-1">
																<span>
																	<div class="svg15 double-check"></div>
																</span>
																<!--Last messsage-->
																<span class="message-shortcut margin-auto text-muted fs-13 ml-1 mr-4">@userDto.FullName</span>
															</div>
														</div>
													</div>
												</div>
												<div class="flex-shrink-0 margin-auto pl-2 pr-3">
													<div class="d-flex flex-column">
														<p class="text-muted text-right fs-13 mb-2">@userDto.CreationTime.Value.ToShortDateString()</p>
														<div class="text-right d-flex flex-row">
															<form method="post" asp-page-handler="AddOther">
																<input type="hidden" asp-for="@Model.AddOtherId" value="@userDto.Id">
																<input type="hidden" asp-for="@Model.CurrentGroupId" />
																<button type="submit">
																	<i class="fa-solid fa-plus fa-beat" style="color: #538ae9;"></i>
																</button>
																<i class="text-muted la la-angle-down ml-1 fs-15"></i>
															</form>
														</div>
													</div>
												</div>
											</div>
										}
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-8 col-12 card-stacked">
						<div class="card shadow-line mb-3 chat chat-panel">
							<div class="p-3 chat-header">
								<div class="d-flex">
									<div class="w-100 d-flex pl-0">
										@if (Model.Others.Count > 0)
										{
											<img class="rounded-circle shadow avatar-sm mr-3 chat-profile-picture" src="~/images/@Model.Others[0].FullName">

										}
										else
										{
											<img class="rounded-circle shadow avatar-sm mr-3 chat-profile-picture" src="~/assets//img/bg-profile.jpg">

										}
										<!--Group name-->
										<div class="mr-3">
											<p class="fw-400 mb-0 text-dark-75">@Model.CurrentGroup.Name</p>
											<p class="sub-caption text-muted text-small mb-0"><i class="la la-clock mr-1"></i>last seen today at 09:15 PM</p>
										</div>
									</div>
									<div class="flex-shrink-0 margin-auto">
										<a href="#" class="btn btn-sm btn-icon btn-light active text-dark ml-2">
											<svg viewBox="0 0 24 24" width="15" height="15" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="feather">
												<circle cx="12" cy="12" r="10"></circle>
												<line x1="12" y1="16" x2="12" y2="12"></line>
												<line x1="12" y1="8" x2="12.01" y2="8"></line>
											</svg>
										</a>
										<a href="#" class="btn btn-sm btn-icon btn-light active text-dark ml-2">
											<svg viewBox="0 0 24 24" width="15" height="15" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="feather">
												<polygon points="23 7 16 12 23 17 23 7"></polygon>
												<rect x="1" y="5" width="15" height="14" rx="2" ry="2"></rect>
											</svg>
										</a>
										<a href="#" class="btn btn-sm btn-icon btn-light active text-dark ml-2">
											<svg viewBox="0 0 24 24" width="15" height="15" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="feather">
												<circle cx="11" cy="11" r="8"></circle>
												<line x1="21" y1="21" x2="16.65" y2="16.65"></line>
											</svg>
										</a>
										<a href="#" class="btn btn-sm btn-icon btn-light active text-dark ml-2">
											<svg viewBox="0 0 24 24" width="15" height="15" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="feather">
												<circle cx="12" cy="12" r="1"></circle>
												<circle cx="12" cy="5" r="1"></circle>
												<circle cx="12" cy="19" r="1"></circle>
											</svg>
										</a>
									</div>
								</div>
							</div>
							<!--MessageBox-->
							<div class="d-flex flex-row mb-3 navigation-mobile scrollable-chat-panel chat-panel-scroll">
								<div class="w-100 p-3 scrollable-chat-panel" id="messageBox">
									<div class="svg36 loader-animate3 horizontal-margin-auto mb-2"></div>
									<div class="text-center letter-space drop-shadow text-uppercase fs-12 w-100 mb-3">Today</div>
									@if (Model.MessageDtos != null)
									{
										@foreach (var item in Model.MessageDtos)
										{
											if (Model.CurrentUser.Id != item.SenderId)
											{
												<!--Left Message-->
												<div class="left-chat-message fs-13 mb-2">
													<p class="mb-3 mr-5 pr-5">@item.Content</p>
													<div class="message-options">
														<div class="message-time">From @item.Sender.FullName: @item.CreationTime.Humanize(utcDate:false)</div>
													</div>

												</div>
											}
											else
											{
												<!--Right Message-->
												<div class="d-flex flex-row-reverse mb-2">
													<div class="right-chat-message fs-13 mb-2">
														<div class="mb-0 mr-3 pr-4">
															<div class="d-flex flex-row">

																<div class="mb-3 mr-5 pr-5">@item.Content</div>
																<div class="pr-4"></div>
															</div>
														</div>
														<div class="message-options dark">
															<div class="message-time">
																<div class="d-flex flex-row">
																	<div class="mr-2">@item.CreationTime.Humanize(utcDate:false)</div>
																	<div class="svg15 double-check"></div>
																</div>
															</div>
															<div class="message-arrow"><i class="text-muted la la-angle-down fs-17"></i></div>
														</div>
													</div>
												</div>
											}
										}
									}
								</div>
							</div>
							<form method="post">
								<div class="chat-search pl-3 pr-3">
									<div class="input-group">
										<!--Input message-->
										<input type="hidden" id="groupId" asp-for="@Model.CurrentGroupId" />
										<input type="hidden" asp-for="@Model.CurrentUser" />
										<input type="hidden" id="currentUser" asp-for="@Model.CurrentUser.UserName" />

										<input id="messageInput" type="text" class="form-control" placeholder="Write a message">
										<div class="input-group-append prepend-white">
											<span class="input-group-text pl-2 pr-2">
												<i class="chat-upload-trigger fs-19 bi bi-file-earmark-plus ml-2 mr-2"></i>
												<i class="fs-19 bi bi-emoji-smile ml-2 mr-2"></i>
												<i class="fs-19 bi bi-camera ml-2 mr-2"></i>
												<!--Send button-->
												<button id="sendButton" type="submit" class="form-control" value="Send"></button>
											</span>
										</div>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>



<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.perfect-scrollbar/0.6.7/js/min/perfect-scrollbar.jquery.min.js"></script>

<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.bundle.min.js"></script>



<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script src="~/js/chat.js"></script>
<script src="~/js/site.js"></script>

PMS_Application/PMS.WebApp/Areas/Callin/Pages/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        @Model
    </div>
}